import { StyleSheet, Platform, StatusBar } from "react-native";
import * as colors from '../theme/colors';

export const aboutStyles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
    paddingTop: 8,
  },
  backButton: {
    marginRight: 12,
    padding: 8,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.COULEUR_WHITE,
    letterSpacing: 0.5,
    flex: 1,
  },
  heroSection: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    shadowColor: '#0F2E5A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
    alignItems: 'center',
  },
  appTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.COULEUR_HEADER_BLEU,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  appSubtitle: {
    fontSize: 15,
    color: colors.COULEUR_SOUS_TITRE,
    fontStyle: 'italic',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  section: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#0F2E5A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderLeftWidth: 4,
    borderLeftColor: colors.COULEUR_HEADER_BLEU,
  },
  sectionWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: 'rgba(74, 144, 226, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 0,
    flexShrink: 0,
  },
  sectionContent: {
    flex: 1,
    marginLeft: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.COULEUR_HEADER_BLEU,
    marginBottom: 0,
    letterSpacing: 0.3,
  },
  sectionText: {
    fontSize: 14,
    color: colors.COULEUR_TEXT_DARK,
    lineHeight: 22,
    letterSpacing: 0.3,
    marginTop: 12,
    marginBottom: 0,
  },
  authorsList: {
    fontSize: 14,
    color: colors.COULEUR_TEXT_DARK,
    fontWeight: '500',
    lineHeight: 24,
    marginTop: 12,
  },
  authorItem: {
    fontSize: 14,
    color: colors.COULEUR_TEXT_DARK,
    marginBottom: 8,
    paddingLeft: 8,
    lineHeight: 20,
  },
  authorBullet: {
    color: colors.COULEUR_HEADER_BLEU,
    fontWeight: '700',
    marginRight: 6,
  },
  highlightText: {
    color: colors.COULEUR_HEADER_BLEU,
    fontWeight: '700',
  },
  logosContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.08)',
  },
  logoWrapper: {
    width: 90,
    height: 90,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(74, 144, 226, 0.2)',
  },
  logo: {
    width: 75,
    height: 75,
    resizeMode: 'contain',
  },
});
