import { StyleSheet, Platform, StatusBar } from "react-native";
import * as colors from '../theme/colors';

export const compteStyles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: 30,
    paddingTop: 20,
  },
  avatarContainer: {
    marginBottom: 15,
    width: 90,
    height: 90,
    borderRadius: 45,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.COULEUR_WHITE,
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  emailText: {
    fontSize: 16,
    color: colors.COULEUR_WHITE,
    opacity: 0.9,
  },
  emailPill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  card: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 18,
    padding: 18,
    marginBottom: 15,
    shadowColor: "#0F2E5A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.6)",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.COULEUR_TEXT_DARK,
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  infoIconContainer: {
    width: 40,
    alignItems: 'center',
    marginRight: 15,
  },
  infoContent: {
    flex: 1,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.08)',
    marginVertical: 4,
  },
  label: {
    fontSize: 13,
    color: colors.COULEUR_SOUS_TITRE,
    marginBottom: 4,
  },
  value: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.COULEUR_TEXT_DARK,
  },
  logoutButton: {
    backgroundColor: colors.COULEUR_BOUTON,
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.COULEUR_BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 10,
  },
  logoutButtonText: {
    color: colors.COULEUR_WHITE,
    fontSize: 16,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    color: colors.COULEUR_WHITE,
    marginTop: 10,
    fontSize: 16,
  },
  noUser: {
    color: colors.COULEUR_WHITE,
    fontSize: 16,
    textAlign: "center",
  },
});

